Ext.define('AM.model.Balance', {
    extend: 'Ext.data.TreeModel',
    fields: [{
        name: 'cta',
        type: 'string'
    }, {
        name: 'text',
        type: 'string'
    /*}, {
        name: 'iconCls',
        type: 'string'
    }, {
        name: 'parent',
        type: 'string'
    }, {
        name: 'id',
        type: 'int'*/
    }, {
        name: 'anomes',
        type: 'int'
    }, {
        name: 'vald',
        type: 'float'
    }, {
        name: 'valc',
        type: 'float'
    /*}, {
        name: 'leaf',
        type: 'boolean'*/
    }]
});